// Mocks generated by Mockito 5.4.2 from annotations
// in daily_quest/test/daily_quest/domain/usecase/get_daily_quest_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:daily_quest/daily_quest/domain/entity/daily_quest.dart' as _i2;
import 'package:daily_quest/daily_quest/domain/helper/quest_validator.dart'
    as _i5;
import 'package:daily_quest/daily_quest/domain/repository/daily_quest_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

import 'get_daily_quest_test.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDailyQuest_0 extends _i1.SmartFake implements _i2.DailyQuest {
  _FakeDailyQuest_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DailyQuestRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDailyQuestRepository extends _i1.Mock
    implements _i3.DailyQuestRepository {
  @override
  _i4.Future<_i2.DailyQuest> getLastDailyQuest() => (super.noSuchMethod(
        Invocation.method(
          #getLastDailyQuest,
          [],
        ),
        returnValue: _i4.Future<_i2.DailyQuest>.value(_FakeDailyQuest_0(
          this,
          Invocation.method(
            #getLastDailyQuest,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.DailyQuest>.value(_FakeDailyQuest_0(
          this,
          Invocation.method(
            #getLastDailyQuest,
            [],
          ),
        )),
      ) as _i4.Future<_i2.DailyQuest>);
  @override
  _i4.Future<void> insertDailyQuest({required _i2.DailyQuest? quest}) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertDailyQuest,
          [],
          {#quest: quest},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [QuestValidator].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuestValidator extends _i1.Mock implements _i5.QuestValidator {
  @override
  bool validate({required _i2.DailyQuest? quest}) => (super.noSuchMethod(
        Invocation.method(
          #validate,
          [],
          {#quest: quest},
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}

/// A class which mocks [TestFunction].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestFunction extends _i1.Mock implements _i6.TestFunction {
  @override
  String call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
}
