// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9LGaIGnPCzPEEpIiBfCAkPTRjBvsGpfM',
    appId: '1:11722392050:android:d1b571f32ff22b9704eb6b',
    messagingSenderId: '11722392050',
    projectId: 'dailyquest-7272a',
    databaseURL: 'https://dailyquest-7272a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dailyquest-7272a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp0VDyuHFnUKJj6OsLhXGPy54OUxA4cb4',
    appId: '1:11722392050:ios:40e5b579489e9e3d04eb6b',
    messagingSenderId: '11722392050',
    projectId: 'dailyquest-7272a',
    databaseURL: 'https://dailyquest-7272a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dailyquest-7272a.appspot.com',
    iosClientId: '11722392050-qufoi74rccfsjh5gu2a13nd27t5bghad.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp0VDyuHFnUKJj6OsLhXGPy54OUxA4cb4',
    appId: '1:11722392050:ios:017cf061b11d26bc04eb6b',
    messagingSenderId: '11722392050',
    projectId: 'dailyquest-7272a',
    databaseURL: 'https://dailyquest-7272a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dailyquest-7272a.appspot.com',
    iosClientId: '11722392050-tmppjclkqlgenenvg337ridoo83lvu0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyQuest.RunnerTests',
  );
}
